routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//general routes
Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/brand/{name}','Frontend\ProductController@brand');
Route::get('/products','Frontend\ProductController@index');
Route::get('/products/search','Frontend\ProductController@search');
Route::get('/singleproduct','Frontend\ProductController@singleProduct');

Route::get('/services', 'Frontend\FrontendController@services')->name('services');
Route::post('/sendServiceMessage', 'Frontend\FrontendController@sendServiceMessage')->name('sendServiceMessage');

Route::get('/get-a-quote', 'Frontend\FrontendController@getQuote')->name('getQuote');
Route::post('/sendquote', 'Frontend\FrontendController@sendQuote')->name('sendQuote');
Route::post('/getProducts', 'Frontend\FrontendController@getProducts')->name('getProducts');

Route::get('/contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('/contactSend', 'Frontend\FrontendController@contactSend')->name('contactSend');

Route::get('/about', 'Frontend\FrontendController@about')->name('about');

Route::get('/gallery/albums','Frontend\FrontendController@albums')->name('gallery.albums');
Route::get('/gallery/album/{slug}', 'Frontend\FrontendController@album')->name('gallery.album');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/home', 'HomeController@index')->name('home');


//routes for admin
Route::prefix('admin')->group(function(){
    Auth::routes();

    Route::get('staffs','Admin\StaffController@index')->name('staffs.index');
    Route::post('staffs/update','Admin\StaffController@update')->name('staffs.update');    
    Route::post('staffs/delete/{id}','Admin\StaffController@destroy')->name('staffs.destroy');
    Route::post('verifyPassword','Admin\StaffController@verifyPassword')->name('verifyPassword');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('services', 'Admin\ServiceController',['except' => ['show']]);

    Route::get('quotations/unseen','Admin\QuotationController@unseenQuotes')->name('quotations.unseen');    
    Route::get('quotations/reply/{id}','Admin\QuotationController@reply')->name('quotations.reply');
    Route::post('quotations/reply/{id}','Admin\QuotationController@replySend')->name('quotations.replySend');
    Route::get('getUnseenQuoteCount','Admin\QuotationController@getUnseenQuoteCount')->name('getUnseenQuoteCount');
    Route::get('getUnseenQuote','Admin\QuotationController@getUnseenQuote')->name('getUnseenQuote');
    Route::resource('quotations', 'Admin\QuotationController',['only' => ['show','destroy','index']]);

    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');

    Route::resource('testimonials', 'Admin\TestimonialController',['only' => ['index','store','edit','update','destroy']]);

    Route::get('contact-us-messages/unseen','Admin\ContactController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactController@getUnseenMsg')->name('getUnseenMsg');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);
    
    Route::get('service-support-messages','Admin\ServiceSupportMessageController@addImages1')->name('service-support-messages.index');
    Route::get('service-support-messages/unseen','Admin\ServiceSupportMessageController@unseenMsg')->name('service-support-messages.unseen');    
    Route::get('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@reply')->name('service-support-messages.reply');
    Route::post('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@replySend')->name('service-support-messages.replySend');
    Route::resource('service-support-messages', 'Admin\ServiceSupportMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenSSMsgCount','Admin\ServiceSupportMessageController@getUnseenSSMsgCount')->name('getUnseenSSMsgCount');
    Route::get('getUnseenSSMsg','Admin\ServiceSupportMessageController@getUnseenSSMsg')->name('getUnseenSSMsg');

    Route::get('/dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::get('/','Admin\AdminController@index');
    
    Route::get('/products/search','ProductController@search');
	Route::post('/products/addbasics','ProductController@addBasics');
	Route::post('/products/editbasics','ProductController@editBasics');
    Route::get('/products/getbrandsandsolutions','ProductController@getBrandsAndSolutions');
	Route::post('/products/addimage/{id}','ProductController@addImage');
    Route::post('/products/removeimage','ProductController@removeImage');
    Route::resource('/products','ProductController');
    Route::post('/products/savefeatures','ProductController@saveFeatures');
    Route::post('/products/savespecification','ProductController@saveSpecification');
    Route::post('/products/savepurpose','ProductController@savePurpose');
    Route::post('/products/savefaqs','ProductController@saveFaqs');
    Route::post('/products/adddriver','ProductController@adddriver');
    Route::post('/products/savedriver','ProductController@savedriver');
    Route::post('/products/removedriver','ProductController@removedriver');
    Route::get('/products/changefeatured/{id}','ProductController@changeFeatured'); 
    Route::get('/products/changestatus/{id}','ProductController@changeStatus'); 
   
	Route::post('/brands/createmainbrand','BrandController@createMainBrand');
    Route::post('/brands/createbrand','BrandController@createBrand');
    Route::get('/brands','BrandController@index')->name('brands.index');
	Route::get('/brands/getbrands','BrandController@getBrands');
	Route::get('/brands/brandsbyid','BrandController@getSingleBrand');
    Route::post('/brands/savebrand','BrandController@saveBrand');
    Route::post('/brands/create','BrandController@addBrand');
	Route::post('/brands/edit','BrandController@editBrand');
	Route::post('/brands/editParent','BrandController@editBrandParent');
	Route::post('/brands/delete','BrandController@deleteBrand');
    Route::get('/brands/editmainbrand/{id}','BrandController@editMainBrand');
    Route::delete('/brands/removeImage/{id}','BrandController@removeImage')->name('admin.brands.removeImage');
    Route::post('/brands/addImage/{id}','BrandController@addImage')->name('admin.brands.addImage');
    Route::post('/brands/haschild','BrandController@hasChild');


	Route::get('/solutions','SolutionController@index')->name('solutions.index');
    Route::get('/solutions/getsolutions','SolutionController@getSolutions');
    Route::get('/solutions/solutionsbyid','SolutionController@getSingleSolution');
    Route::post('/solutions/create','SolutionController@addSolution');
    Route::post('/solutions/edit','SolutionController@editSolution');
    Route::post('/solutions/editParent','SolutionController@editSolutionParent');
    Route::post('/solutions/delete','SolutionController@deleteSolution');
    Route::post('/solutions/createSolution','SolutionController@createSolution');
    Route::post('/solutions/haschild','SolutionController@hasChild');    
});

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    public function album_images()
    {
        return $this->hasMany('App\Gallery');
    }
}

app/Http/Controllers/Admin/AlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Album;
use App\Gallery;
use Auth;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Request $request)
    {
        $this->middleware('auth');
        $this->middleware(function ($request, $next) {

            if (Auth::user()->roles()->where('title', '=', 'Albums')->exists()){
                return $next($request);
            }
            else
                abort(403);
        });
    }

    public function index()
    {
        $albums = Album::orderBy('year','desc')->orderBy('created_at','desc')->get();
        return view('admin.albums.index')->with('albums',$albums);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(array(
            'name'=>'required|max:191',
            'year'=> 'required'
        ),array(
            'name.required' => 'Album name is required',
            'year.required' => 'ALbum year is required'
        ));

        $i = 1;
        $name = $request->name;
        while(Album::where('name', $name)->where('year', $request->year)->exists()){
            $name = $request->name. '('.$i.')';
            $i++;
        }
        
        $slug = str_replace(' ','-',strtolower($name));
        $album = new Album;
        $album->name = $name;
        $album->year = $request->year;
        $album->slug = $slug.'-'.$request->year;

        $album->save();

        $request->session()->flash('success', 'New album created');

        return redirect()->route('albums.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $album = Album::find($id);
        if(!$album)
            abort(404);
        return view('admin.albums.show')->with('album',$album);
    }

    public function addImages($id,Request $request){
        if($request->hasFile('files')){
            $images = $request->file('files');  
        }

        $count = 0;
        foreach($images as $image){
            $gallery = new Gallery;
            $filename = time().'G'.$count++ . '.' . $image->getClientOriginalExtension();
            $location = public_path('gallery/');
            $image->move($location,$filename);
            $gallery->image = $filename;
            $gallery->album_id = $id;
            $gallery->save();
        }
        
        $request->session()->flash('success', 'Images Uploaded');
        return;
    }
    public function deleteImage($album_id, $image_id,Request $request)
    {
        $gallery = Gallery::find($image_id);
        unlink(public_path('gallery/'.$gallery->image));
        $gallery->delete();

        $request->session()->flash('success', 'Image Deleted');
        return redirect()->route('albums.show',$album_id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(array(
            'editname'=>'required|max:191',
            'edityear'=> 'required'
        ),array(
            'editname.required' => 'Album name is required',
            'edityear.required' => 'ALbum year is required'
        ));


        $i = 1;
        $name = $request->editname;
        $album = Album::find($id);
        if($name != $album->name){
            while(Album::where('name', $name)->where('year', $request->edityear)->exists()){
                $name = $request->editname. '('.$i.')';
                $i++;
            }
        }
        
        $slug = str_replace(' ','-',strtolower($name));
        
        $album->name = $name;
        $album->year = $request->edityear;
        $album->slug = $slug.'-'.$request->edityear;
        $album->save();

        $request->session()->flash('success', 'Album upated');

        return redirect()->route('albums.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,Request $request)
    {
        $album = Album::find($id);
        foreach($album->album_images as $image){
            unlink(public_path('gallery/'.$image->image));
        }
        $album->delete();

        $request->session()->flash('success', 'Album deleted');

        return redirect()->route('albums.index');
    }
}

resources/views/admin/albums/index.blade.php
 @extends('layouts.admin')

 @section('body')
  
    <div class="app-content content container-fluid">
        <div class="content-wrapper">
            @if (count($errors)>0 )
                <div class="alert alert-dismissible fade in mb-2">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true" style="color:black">&times;</span>
                    </button>
                    <ul class="list-group">
                        @foreach ($errors->all() as $error)
                            <li class="list-group-item list-group-item-danger">{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>	
            @endif
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-xs-12 mb-1">
                    <h2 class="content-header-title">Albums</h2>
                </div>
                <div class="text-xs-right">
                    <button class="btn btn-primary btn-min-width mr-2 mb-1" data-toggle="modal" data-target="#addAlbum">Add new Album</button>
                </div>
            </div>
            <div class="content-body">
                
                <div class="card">
                    <div class="card-body collapse in">
                        <div class="card-block card-dashboard">
                            <div class="row">

                                @foreach($albums as $album)
                                    <div class="col-xl-3 col-md-6 col-sm-12 " style="margin-bottom:10px">
                                        <?php $images = $album->album_images()->limit(3)->get(); ?>
                                        <a href="{{ route('albums.show',$album->id) }}">
                                            @if(count($images)>0)
                                                <div id="carousel-wrap{{$album->id}}" class="carousel slide" data-ride="carousel" data-wrap="false" style="height:200px;width:200px">
                                                    <ol class="carousel-indicators">
                                                        @foreach($images as $i)
                                                            <li data-target="#carousel-wrap{{$album->id}}" data-slide-to="{{$loop->iteration-1}}" class="{{$loop->iteration==1?'active':''}}"></li>
                                                        @endforeach
                                                    </ol>
                                                    <div class="carousel-inner" role="listbox">
                                                        @foreach($images as $i)
                                                            <div class="carousel-item {{$loop->iteration==1?'active':''}}">
                                                                <img src="{{ route('asset', ['gallery',$i->image,200,200]) }}" alt="{{$loop->iteration}} slide">
                                                            </div>
                                                        @endforeach
                                                    </div>
                                                    <a class="left carousel-control" href="#carousel-wrap{{$album->id}}" role="button" data-slide="prev">
                                                        <span class="icon-prev" aria-hidden="true"></span>
                                                        <span class="sr-only">Previous</span>
                                                    </a>
                                                    <a class="right carousel-control" href="#carousel-wrap{{$album->id}}" role="button" data-slide="next">
                                                        <span class="icon-next" aria-hidden="true"></span>
                                                        <span class="sr-only">Next</span>
                                                    </a>
                                                </div>
                                            @else
                                                <img src="/gallery.jpg" style="height:200px;width:200px"/><br>
                                            @endif
                                        </a><br>
                                        <a href="{{ route('albums.show',$album->id) }}"><h4 class="card-title ">{{ $album->name }} - {{ $album->year }}</h4></a>

                                        <a class="btn btn-outline-warning" onclick="editAlbum({{ $album }})"><i class="icon-edit"></i></a>
                                    
                                        <form action="{{ route('albums.destroy',$album->id) }}" method="POST" style="display:inline">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE" >
                                            <button id='deleteAlbum' type="button" class="btn btn-outline-danger" ><a><i class="icon-trash-o"></i></a></button>
                                        </form>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade text-xs-left" id="addAlbum" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form" method="POST" action="{{ route('albums.store') }}">
                    <div class="modal-body">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <h4 class="form-section">Add New Album</h4>
                            <div class="form-group">
                                <label for="name">Album name</label>
                                <input class="form-control " id="name" type="text" placeholder="Album Name"  name="name" required>
                            </div>

                            <div class="form-group">
                                <label for="year">Album Year</label>
                                <select class="form-control " id="year" placeholder="Album Year"  name="year" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                </form>                                    
            </div>
        </div>
    </div>
    <div class="modal fade text-xs-left" id="editAlbum" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form" method="POST" id="editAlbumForm" action="">
                    <input type="hidden" name="_method" value="PATCH" >
                    <div class="modal-body">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <h4 class="form-section">Edit Album</h4>
                            <div class="form-group">
                                <label for="editname">Album name</label>
                                <input class="form-control " id="editname" type="text" placeholder="Album Name"  name="editname" required>
                            </div>

                            <div class="form-group">
                                <label for="edityear">Album Year</label>
                                <select class="form-control " id="edityear" placeholder="Album Year"  name="edityear" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                </form>                                    
            </div>
        </div>
    </div>
    
 @endsection

 @section('js')
    <script>
        $(document).ready(function(){
            var current = parseInt(new Date().getFullYear());
            var html;
            for(var i=0;i<10;i++){
                html = "<option id='"+(current-i)+"'>"+(current-i)+"</option>";
                $('#year').append(html);
                $('#edityear').append(html);
            }
        });

        function editAlbum(album){
            $('#editAlbumForm').attr('action',"{{ URL::to('/admin/albums/')}}"+"/"+album.id);
            $("input[name='editname']").val(album.name);
            $("select[name='edityear']").val(album.year);
            $('#editAlbum').modal('show');
        }
    </script>
 @endsection