routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//general routes
Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/brand/{name}','Frontend\ProductController@brand');
Route::get('/products','Frontend\ProductController@index');
Route::get('/products/search','Frontend\ProductController@search');
Route::get('/singleproduct','Frontend\ProductController@singleProduct');

Route::get('/services', 'Frontend\FrontendController@services')->name('services');
Route::post('/sendServiceMessage', 'Frontend\FrontendController@sendServiceMessage')->name('sendServiceMessage');

Route::get('/get-a-quote', 'Frontend\FrontendController@getQuote')->name('getQuote');
Route::post('/sendquote', 'Frontend\FrontendController@sendQuote')->name('sendQuote');
Route::post('/getProducts', 'Frontend\FrontendController@getProducts')->name('getProducts');

Route::get('/contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('/contactSend', 'Frontend\FrontendController@contactSend')->name('contactSend');

Route::get('/about', 'Frontend\FrontendController@about')->name('about');

Route::get('/gallery/albums','Frontend\FrontendController@albums')->name('gallery.albums');
Route::get('/gallery/album/{slug}', 'Frontend\FrontendController@album')->name('gallery.album');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/home', 'HomeController@index')->name('home');


//routes for admin
Route::prefix('admin')->group(function(){
    Auth::routes();

    Route::get('staffs','Admin\StaffController@index')->name('staffs.index');
    Route::post('staffs/update','Admin\StaffController@update')->name('staffs.update');    
    Route::post('staffs/delete/{id}','Admin\StaffController@destroy')->name('staffs.destroy');
    Route::post('verifyPassword','Admin\StaffController@verifyPassword')->name('verifyPassword');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('services', 'Admin\ServiceController',['except' => ['show']]);

    Route::get('quotations/unseen','Admin\QuotationController@unseenQuotes')->name('quotations.unseen');    
    Route::get('quotations/reply/{id}','Admin\QuotationController@reply')->name('quotations.reply');
    Route::post('quotations/reply/{id}','Admin\QuotationController@replySend')->name('quotations.replySend');
    Route::get('getUnseenQuoteCount','Admin\QuotationController@getUnseenQuoteCount')->name('getUnseenQuoteCount');
    Route::get('getUnseenQuote','Admin\QuotationController@getUnseenQuote')->name('getUnseenQuote');
    Route::resource('quotations', 'Admin\QuotationController',['only' => ['show','destroy','index']]);

    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');

    Route::resource('testimonials', 'Admin\TestimonialController',['only' => ['index','store','edit','update','destroy']]);

    Route::get('contact-us-messages/unseen','Admin\ContactController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactController@getUnseenMsg')->name('getUnseenMsg');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);
    
    Route::get('service-support-messages','Admin\ServiceSupportMessageController@addImages1')->name('service-support-messages.index');
    Route::get('service-support-messages/unseen','Admin\ServiceSupportMessageController@unseenMsg')->name('service-support-messages.unseen');    
    Route::get('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@reply')->name('service-support-messages.reply');
    Route::post('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@replySend')->name('service-support-messages.replySend');
    Route::resource('service-support-messages', 'Admin\ServiceSupportMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenSSMsgCount','Admin\ServiceSupportMessageController@getUnseenSSMsgCount')->name('getUnseenSSMsgCount');
    Route::get('getUnseenSSMsg','Admin\ServiceSupportMessageController@getUnseenSSMsg')->name('getUnseenSSMsg');

    Route::get('/dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::get('/','Admin\AdminController@index');
    
    Route::get('/products/search','ProductController@search');
	Route::post('/products/addbasics','ProductController@addBasics');
	Route::post('/products/editbasics','ProductController@editBasics');
    Route::get('/products/getbrandsandsolutions','ProductController@getBrandsAndSolutions');
	Route::post('/products/addimage/{id}','ProductController@addImage');
    Route::post('/products/removeimage','ProductController@removeImage');
    Route::resource('/products','ProductController');
    Route::post('/products/savefeatures','ProductController@saveFeatures');
    Route::post('/products/savespecification','ProductController@saveSpecification');
    Route::post('/products/savepurpose','ProductController@savePurpose');
    Route::post('/products/savefaqs','ProductController@saveFaqs');
    Route::post('/products/adddriver','ProductController@adddriver');
    Route::post('/products/savedriver','ProductController@savedriver');
    Route::post('/products/removedriver','ProductController@removedriver');
    Route::get('/products/changefeatured/{id}','ProductController@changeFeatured'); 
    Route::get('/products/changestatus/{id}','ProductController@changeStatus'); 
   
	Route::post('/brands/createmainbrand','BrandController@createMainBrand');
    Route::post('/brands/createbrand','BrandController@createBrand');
    Route::get('/brands','BrandController@index')->name('brands.index');
	Route::get('/brands/getbrands','BrandController@getBrands');
	Route::get('/brands/brandsbyid','BrandController@getSingleBrand');
    Route::post('/brands/savebrand','BrandController@saveBrand');
    Route::post('/brands/create','BrandController@addBrand');
	Route::post('/brands/edit','BrandController@editBrand');
	Route::post('/brands/editParent','BrandController@editBrandParent');
	Route::post('/brands/delete','BrandController@deleteBrand');
    Route::get('/brands/editmainbrand/{id}','BrandController@editMainBrand');
    Route::delete('/brands/removeImage/{id}','BrandController@removeImage')->name('admin.brands.removeImage');
    Route::post('/brands/addImage/{id}','BrandController@addImage')->name('admin.brands.addImage');
    Route::post('/brands/haschild','BrandController@hasChild');


	Route::get('/solutions','SolutionController@index')->name('solutions.index');
    Route::get('/solutions/getsolutions','SolutionController@getSolutions');
    Route::get('/solutions/solutionsbyid','SolutionController@getSingleSolution');
    Route::post('/solutions/create','SolutionController@addSolution');
    Route::post('/solutions/edit','SolutionController@editSolution');
    Route::post('/solutions/editParent','SolutionController@editSolutionParent');
    Route::post('/solutions/delete','SolutionController@deleteSolution');
    Route::post('/solutions/createSolution','SolutionController@createSolution');
    Route::post('/solutions/haschild','SolutionController@hasChild');    
});

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

resources/views/admin/dashboard.blade.php
solutions
 @extends('layouts.admin')

 @section('body')
    <div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
        </div>
        <div class="content-body"><!-- stats -->
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-block">
                                <div class="media">
                                    <div class="media-body text-xs-left">
                                        <h3 class="pink">{{$totalProducts}}</h3>
                                        <span>Total Products</span>
                                    </div>
                                    <div class="media-right media-middle">
                                        <i class="icon-bag2 pink font-large-2 float-xs-right"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-block">
                                <div class="media">
                                    <div class="media-body text-xs-left">
                                        <h3 class="teal">{{$totalQuotations}}</h3>
                                        <span>Quotations</span>
                                    </div>
                                    <div class="media-right media-middle">
                                        <i class="icon-user1 teal font-large-2 float-xs-right"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-block">
                                <div class="media">
                                    <div class="media-body text-xs-left">
                                        <h3 class="deep-orange">{{$totalSupports}}</h3>
                                        <span>Support Request</span>
                                    </div>
                                    <div class="media-right media-middle">
                                        <i class="icon-diagram deep-orange font-large-2 float-xs-right"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-xs-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-block">
                                <div class="media">
                                    <div class="media-body text-xs-left">
                                        <h3 class="cyan">{{$totalMessages}}</h3>
                                        <span>Messages</span>
                                    </div>
                                    <div class="media-right media-middle">
                                        <i class="icon-ios-help-outline cyan font-large-2 float-xs-right"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--/ stats -->
           
            <!-- Recent invoice with Statistics -->
            <div class="row match-height">
                <div class="col-xl-4 col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="media">
                                <div class="p-2 text-xs-center bg-deep-orange media-left media-middle">
                                    <i class="icon-user1 font-large-2 white"></i>
                                </div>
                                <div class="p-2 media-body">
                                    <h5 class="deep-orange">Total Subscribers</h5>
                                    <h5 class="text-bold-400">{{$totalSubscribers}}</h5>
                                 </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="media">
                                <div class="p-2 text-xs-center bg-cyan media-left media-middle">
                                    <i class="icon-camera7 font-large-2 white"></i>
                                </div>
                                <div class="p-2 media-body">
                                    <h5>Admin Staffs</h5>
                                    <h5 class="text-bold-400">{{$totalStaffs}}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="media">
                                <div class="p-2 text-xs-center bg-deep-orange media-left media-middle">
                                    <i class="icon-user1 font-large-2 white"></i>
                                </div>
                                <div class="p-2 media-body">
                                    <h5 class="deep-orange">Total Services</h5>
                                    <h5 class="text-bold-400">{{$totalServices}}</h5>
                                 </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-8 col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Recent Quotations</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card-block">
                                <p>showing recent 5 quotations<span class="float-xs-right"><a href="/admin/quotations">view all <i class="icon-arrow-right2"></i></a></span></p>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover mb-0">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Customer Name</th>
                                            <th>Status</th>
                                            <th>Received Date</th>
                                          </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($quotations as $q)
                                        <tr>
                                            <td class="text-truncate"><a href="#">QUO_{{$q->id}}</a></td>
                                            <td class="text-truncate">{{$q->customer_name}}</td>
                                            <td class="text-truncate"><span class="tag tag-default tag-success">{{$q->status?'read':'unread'}}</span></td>
                                            <td class="text-truncate">{{$q->created_at}}</td>
                                        </tr>
                                       @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Recent invoice with Statistics -->
       
                     <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Recent Support Request</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card-block">
                                <p>showing recent 5 support requests <span class="float-xs-right"><a href="/admin/service-support-messages">view all <i class="icon-arrow-right2"></i></a></span></p>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover mb-0">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Customer Name</th>
                                            <th>Status</th>
                                            <th>Received Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($supportmessages as $s)
                                        <tr>
                                            <td class="text-truncate"><a href="#">SUP_{{$s->id}}</a></td>
                                            <td class="text-truncate">{{$s->name}}</td>
                                             <td class="text-truncate"><span class="tag tag-default tag-success">{{$q->status?'read':'unread'}}</span></td>
                                            <td class="text-truncate">{{$s->created_at}}</td>
                                        </tr>
                                        @endforeach
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                     <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Recent Messages</h4>
                            <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="reload"><i class="icon-reload"></i></a></li>
                                    <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="card-block">
                                <p>showing recent 5 messages <span class="float-xs-right"><a href="/admin/contact-us-messages">view all <i class="icon-arrow-right2"></i></a></span></p>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover mb-0">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Customer Name</th>
                                            <th>Status</th>
                                            <th>Received Date</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($messages as $s)
                                        <tr>
                                            <td class="text-truncate"><a href="#">MSG_{{$s->id}}</a></td>
                                            <td class="text-truncate">{{$s->name}}</td>
                                             <td class="text-truncate"><span class="tag tag-default tag-success">{{$q->status?'read':'unread'}}</span></td>
                                            <td class="text-truncate">{{$s->created_at}}</td>
                                        </tr>
                                        @endforeach
 
                                    </tbody>
                                </table>
                            </div>
                       
                    </div>
                </div>
          

        </div>
      </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    
    
@endsection

resources/views/admin/testimonials.blade.php
@extends('layouts.admin')

@section('body')
 <div class="app-content content container-fluid">
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-xs-12 mb-1">
                <h2 class="content-header-title">Testimonials</h2>
            </div>
        </div>
        <div class="row match-height">
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-block">
                        @if($state == 'Add')
                            <form class="form" method="POST" action="{{ route('testimonials.store') }}"  enctype="multipart/form-data">
                        @else
                            <form class="form" method="POST" action="{{ route('testimonials.update',$testimonial_->id) }}"  enctype="multipart/form-data">                            
                            <input type="hidden" name="_method" value="PATCH" >
                        @endif
                                {{ csrf_field() }}
                                
                                <div class="form-group">
                                    <label for="name"><strong>Name:</strong></label>
                                    @if ($errors->has('name'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                    <input type="text" id="name" class="form-control" name="name" value="{{ $testimonial_->name }}" required/>
                                </div>

                                <div class="form-group">
                                    <label for="profession"><strong>Profession:</strong></label>
                                    @if ($errors->has('profession'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('profession') }}</strong>
                                        </div>
                                    @endif
                                    <input type="text" id="profession" class="form-control" name="profession" value="{{ $testimonial_->profession }}" required/>
                                </div>

                                <div class="form-group">
                                    <label for="photo"><strong>{{ $state=='Add'?'':'Current ' }}Image <span class="text-muted">(Optional)</span>: </strong></label> {{ $testimonial_->photo }}
                                    @if ($errors->has('photo'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('photo') }}</strong>
                                        </div>
                                    @endif
                                    <input type="file" id="photo" class="form-control" name="photo"/>
                                </div>
                                <div class="form-group">
                                    <label><strong>New Testimonial:</strong></label>
                                    @if ($errors->has('content'))
                                        <div class="alert alert-danger no-border mb-2">
                                            <strong>{{ $errors->first('content') }}</strong>
                                        </div>
                                    @endif
                                
                                    <textarea class="form-control" rows='6' id="content" name="content" required>{{ $testimonial_->content }}</textarea>

                                </div>
                                <div class="form-actions right">
                                    <button type="submit" class="btn btn-primary">
                                        <i class="icon-check2"></i> {{ $state=="Add"?"Add New":"Save" }}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @foreach($testimonials as $testimonial)
                <div class="col-xl-4 col-md-6 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-block">
                                <h4 class="card-title">{{ $testimonial->name }}</h4>
                                <h6 class="card-subtitle text-muted">{{ $testimonial->profession }}</h6>
                                @if($testimonial->photo)
                                    <img class="img-fluid my-1" src="{{ route('asset', ['landing_images',$testimonial->photo,290,217]) }}" alt="Card image cap">
                                @else
                                    <img class="img-fluid my-1" src="{{ route('asset2', ['images','avatar.png','png',290,217]) }}" alt="{{ $testimonial->name }}"/>
                                @endif
                                <p class="card-text">{{ $testimonial->content }}</p>

                                <a href="{{ route('testimonials.edit',$testimonial->id) }}" class="btn btn-outline btn-warning">Edit</a>
                                
                                <form action="{{ route('testimonials.destroy',$testimonial->id) }}" style="display:inline" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE" >
                                    <button id='deleteTestimonial' type="button" class="btn btn-outline btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection