routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//general routes
Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/brand/{name}','Frontend\ProductController@brand');
Route::get('/products','Frontend\ProductController@index');
Route::get('/products/search','Frontend\ProductController@search');
Route::get('/singleproduct','Frontend\ProductController@singleProduct');

Route::get('/services', 'Frontend\FrontendController@services')->name('services');
Route::post('/sendServiceMessage', 'Frontend\FrontendController@sendServiceMessage')->name('sendServiceMessage');

Route::get('/get-a-quote', 'Frontend\FrontendController@getQuote')->name('getQuote');
Route::post('/sendquote', 'Frontend\FrontendController@sendQuote')->name('sendQuote');
Route::post('/getProducts', 'Frontend\FrontendController@getProducts')->name('getProducts');

Route::get('/contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('/contactSend', 'Frontend\FrontendController@contactSend')->name('contactSend');

Route::get('/about', 'Frontend\FrontendController@about')->name('about');

Route::get('/gallery/albums','Frontend\FrontendController@albums')->name('gallery.albums');
Route::get('/gallery/album/{slug}', 'Frontend\FrontendController@album')->name('gallery.album');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/home', 'HomeController@index')->name('home');


//routes for admin
Route::prefix('admin')->group(function(){
    Auth::routes();

    Route::get('staffs','Admin\StaffController@index')->name('staffs.index');
    Route::post('staffs/update','Admin\StaffController@update')->name('staffs.update');    
    Route::post('staffs/delete/{id}','Admin\StaffController@destroy')->name('staffs.destroy');
    Route::post('verifyPassword','Admin\StaffController@verifyPassword')->name('verifyPassword');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('services', 'Admin\ServiceController',['except' => ['show']]);

    Route::get('quotations/unseen','Admin\QuotationController@unseenQuotes')->name('quotations.unseen');    
    Route::get('quotations/reply/{id}','Admin\QuotationController@reply')->name('quotations.reply');
    Route::post('quotations/reply/{id}','Admin\QuotationController@replySend')->name('quotations.replySend');
    Route::get('getUnseenQuoteCount','Admin\QuotationController@getUnseenQuoteCount')->name('getUnseenQuoteCount');
    Route::get('getUnseenQuote','Admin\QuotationController@getUnseenQuote')->name('getUnseenQuote');
    Route::resource('quotations', 'Admin\QuotationController',['only' => ['show','destroy','index']]);

    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');

    Route::resource('testimonials', 'Admin\TestimonialController',['only' => ['index','store','edit','update','destroy']]);

    Route::get('contact-us-messages/unseen','Admin\ContactController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactController@getUnseenMsg')->name('getUnseenMsg');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);
    
    Route::get('service-support-messages','Admin\ServiceSupportMessageController@addImages1')->name('service-support-messages.index');
    Route::get('service-support-messages/unseen','Admin\ServiceSupportMessageController@unseenMsg')->name('service-support-messages.unseen');    
    Route::get('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@reply')->name('service-support-messages.reply');
    Route::post('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@replySend')->name('service-support-messages.replySend');
    Route::resource('service-support-messages', 'Admin\ServiceSupportMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenSSMsgCount','Admin\ServiceSupportMessageController@getUnseenSSMsgCount')->name('getUnseenSSMsgCount');
    Route::get('getUnseenSSMsg','Admin\ServiceSupportMessageController@getUnseenSSMsg')->name('getUnseenSSMsg');

    Route::get('/dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::get('/','Admin\AdminController@index');
    
    Route::get('/products/search','ProductController@search');
	Route::post('/products/addbasics','ProductController@addBasics');
	Route::post('/products/editbasics','ProductController@editBasics');
    Route::get('/products/getbrandsandsolutions','ProductController@getBrandsAndSolutions');
	Route::post('/products/addimage/{id}','ProductController@addImage');
    Route::post('/products/removeimage','ProductController@removeImage');
    Route::resource('/products','ProductController');
    Route::post('/products/savefeatures','ProductController@saveFeatures');
    Route::post('/products/savespecification','ProductController@saveSpecification');
    Route::post('/products/savepurpose','ProductController@savePurpose');
    Route::post('/products/savefaqs','ProductController@saveFaqs');
    Route::post('/products/adddriver','ProductController@adddriver');
    Route::post('/products/savedriver','ProductController@savedriver');
    Route::post('/products/removedriver','ProductController@removedriver');
    Route::get('/products/changefeatured/{id}','ProductController@changeFeatured'); 
    Route::get('/products/changestatus/{id}','ProductController@changeStatus'); 
   
	Route::post('/brands/createmainbrand','BrandController@createMainBrand');
    Route::post('/brands/createbrand','BrandController@createBrand');
    Route::get('/brands','BrandController@index')->name('brands.index');
	Route::get('/brands/getbrands','BrandController@getBrands');
	Route::get('/brands/brandsbyid','BrandController@getSingleBrand');
    Route::post('/brands/savebrand','BrandController@saveBrand');
    Route::post('/brands/create','BrandController@addBrand');
	Route::post('/brands/edit','BrandController@editBrand');
	Route::post('/brands/editParent','BrandController@editBrandParent');
	Route::post('/brands/delete','BrandController@deleteBrand');
    Route::get('/brands/editmainbrand/{id}','BrandController@editMainBrand');
    Route::delete('/brands/removeImage/{id}','BrandController@removeImage')->name('admin.brands.removeImage');
    Route::post('/brands/addImage/{id}','BrandController@addImage')->name('admin.brands.addImage');
    Route::post('/brands/haschild','BrandController@hasChild');


	Route::get('/solutions','SolutionController@index')->name('solutions.index');
    Route::get('/solutions/getsolutions','SolutionController@getSolutions');
    Route::get('/solutions/solutionsbyid','SolutionController@getSingleSolution');
    Route::post('/solutions/create','SolutionController@addSolution');
    Route::post('/solutions/edit','SolutionController@editSolution');
    Route::post('/solutions/editParent','SolutionController@editSolutionParent');
    Route::post('/solutions/delete','SolutionController@deleteSolution');
    Route::post('/solutions/createSolution','SolutionController@createSolution');
    Route::post('/solutions/haschild','SolutionController@hasChild');    
});

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
      public function features()
    {
        return $this->hasMany('App\Feature');
    }
      public function faqs()
    {
        return $this->hasMany('App\Faq');
    }
      public function drivers()
    {
        return $this->hasMany('App\Driver');
    }
     public function productimages()
    {
        return $this->hasMany('App\Productimage');
    }
    
    public function brand()
    {
      return $this->belongsTo('App\Brand');
    }
}

app/Http/Controllers/Frontend/ProductController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Brand;
use App\Solution;
use App\Product;

class ProductController extends Controller
{

	public function index(Request $request)
	{
		$cid=$request->cid;
		$bid=$request->bid;
		$filtype=$request->filtype;
		$breadcrumbs=$this->getBreadcrumbs($cid,$filtype);

		// dd($breadcrumbs);
		$products=$this->getProducts($cid,$filtype);
		usort($products, function($a, $b)	
		{
		    return strcmp($a->priority, $b->priority);
		});
		// dd($products);
		$category=$this->getCategory($cid,$filtype);
		$childs=$this->getChilds($cid,$filtype);

		// dd($products);
		// dd(sizeof($breadcrumbs));
		return view('frontend.product',compact('breadcrumbs','products','category','childs','filtype','bid'));
	}

	public function search(Request $request)
	{
		$bid=$request->bid;
		$products=Product::where('name','LIKE','%'.$request->key.'%')->get();
		$breadcrumbs=json_decode($request->breadcrumbs);
		$category=json_decode($request->category);
		$filtype=$request->filtype;
		// dd($request->filtype);
		$key=$request->key;
		return view('frontend.search',compact('breadcrumbs','products','category','filtype','bid','key'));
	}

	public function brand($name)
	{
		$brand=Brand::where('name',$name)->with('brandimages')->first();
		if(!$brand) abort(404);

		$filtype="brand";
		$bid=$brand->id;
		// dd($brand);
		return view('frontend.brand',compact('brand','filtype','bid'));
	}

	public function singleProduct(Request $request)
	{
		$cid="";
		if($request->filtype=="brand")
			$cid=Product::where('id',$request->id)->first()->brand_id;
		else
			$cid=Product::where('id',$request->id)->first()->solution_id;
		dd($cid);
		// if(!$cid) abort(404);

		$bid=$request->bid;
		$breadcrumbs=$this->getBreadcrumbs($cid,$request->filtype);
		$filtype=$request->filtype;
		$product=Product::where('id',$request->id)->with('features')->with('faqs')->with('drivers')->with('brand')->first();
		$bid=0;
		$pid=$product->brand_id;
		while($pid!=0)
		{
			$bid=$pid;
			$pid=Brand::where('id',$pid)->first()->parent_id;
		}
		// dd($bid);
		$brandname=Brand::where('id',$bid)->first()->name;
		return view('frontend.singleproduct',compact('breadcrumbs','product','filtype','bid','brandname'));
		// dd($product);
	}

	private function getBreadcrumbs($cid,$filtype)
	{
		$bc=array();
		$pid=$cid;
		while($pid!=0)
		{
			$cat=(object)[];
			if($filtype=='brand')
				$cat=Brand::where('id',$pid)->first();
			else if($filtype=='solution')
				$cat=Solution::where('id',$pid)->first();
			else
				abort(404);
			if(!$cat) abort(404);
			array_unshift($bc, $cat);
			$pid=$cat->parent_id;
		}

		return $bc;
	}
	private function getProducts($cid,$filtype)
	{
		$arr=array();
		$cat=(object)[];
		if($filtype=='brand')
		{	
			$cat=Brand::where('id',$cid)->first();
			if(!$cat) abort(404);
			if(Brand::where('parent_id',$cat->id)->count()==0)
			{

				$pds=Product::where('brand_id',$cat->id)->where('status','active')->with('productimages')->get();
				// dd($cat->id);
				foreach ($pds as $p) {
					array_push($arr, $p);
				}
				
				return $arr;
			}
			else
			{
				$childs=Brand::where('parent_id',$cat->id)->get();
				foreach ($childs as $c) {
					$a=$this->getProducts($c->id,$filtype);
					$arr=array_merge($arr,$a);
				}

				
			}
		}
		else
		{
			$cat=Solution::where('id',$cid)->first();
			if(!$cat) abort(404);
			if(Solution::where('parent_id',$cat->id)->count()==0)
			{
				$pds=Product::where('solution_id',$cat->id)->where('status','active')->with('productimages')->get();
				// dd($cat->id);
				foreach ($pds as $p) {
					array_push($arr, $p);
				}
				
				return $arr;
			}
			else
			{
				$childs=Solution::where('parent_id',$cat->id)->get();
				foreach ($childs as $c) {
					$a=$this->getProducts($c->id,$filtype);
					$arr=array_merge($arr,$a);
				}

				
			}
		}
		return $arr;
	}
	private function getCategory($cid,$filtype)
	{
		if($filtype=='brand')
			return Brand::where('id',$cid)->first();
		else if($filtype=='solution')
			return Solution::where('id',$cid)->first();
	}
	private function getChilds($cid,$filtype)
	{
		if($filtype=='brand')
			return Brand::where('parent_id',$cid)->get();
		else if($filtype=='solution')
			return Solution::where('parent_id',$cid)->get();
	}
}

resources/views/admin/product/form.blade.php
@extends('layouts.admin')

@section('body')
 <div class="app-content content container-fluid" ng-app="ProductApp" ng-controller="ProductController" ng-init="getBrandsAndSolutions()">
<div class="content-wrapper">
<div class="content-header row">
<div class="content-header-left col-md-6 col-xs-12 mb-1">
<h2 class="content-header-title">Add Product</h2>
</div>

</div>
<div class="row match-height">
<div class="col-xs-12">
<div class="card">
<div class="card-header">
	<h4 class="card-title">Enter Details</h4>
</div>
<div class="card-body">
	<div class="card-block">
	<ul class="nav nav-tabs nav-justified">
		<li class="nav-item">
			<a class="nav-link active" id="basic-tab" data-toggle="tab" href="#basic" aria-controls="basic" aria-expanded="true">Basics</a>
		</li>
		
	</ul>
	<div class="tab-content px-1 pt-1">
		<div role="tabpanel" class="tab-pane fade active in" id="basic" aria-labelledby="basic-tab" aria-expanded="true">
							
		<form class="form" ng-submit="basicSubmit()">
			<div class="form-body">
				<h4 class="form-section"><i class="icon-head"></i>Product Information</h4>
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label for="modelname">Model Name</label>
							<input required ng-model="product.name" type="text" id="modelname" class="form-control" placeholder="Model Name" name="fname">
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label for="brochure">Brochure</label>
							<input type="file" id="brochure" fileread="brochure" class="form-control">
						</div>
					</div>
				</div>
				
				
				<div class="form-group">
					<label for="description">Description</label>
					<textarea required ng-model="product.description" id="description" rows="5" class="form-control" name="comment" placeholder="About Product"></textarea>
				</div>

				<h4 class="form-section"><i class="icon-head"></i>Priority</h4>
				<div class="form-group">
					<label for="issueinput5">Select Priority:<span>1 for highest</span></label>
					<select required id="priority" name="priority" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5" selected>5</option>
					</select>
				</div>


				<h4 class="form-section"><i class="icon-head"></i>Brand Category</h4>
				<div class="form-group">
					<label for="issueinput5">Select Category:</label>
					<select  ng-repeat="lvl in brandlevels" ng-model="lvl['model']" id="brandselect@{{lvl['level']}}" ng-change="brandchange(lvl['level'])" name="priority" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
						<option ng-repeat="l in lvl['vals']" value="@{{l.id}}">@{{l.name}}</option>
					</select>
				</div>

				<h4 class="form-section"><i class="icon-head"></i>Solution Category</h4>
				<div class="form-group">
					<label for="issueinput5">Select Category:</label>
					<select ng-repeat="lvl in solutionlevels" ng-model="lvl['model']" id="solutionselect@{{lvl['level']}}" ng-change="solutionchange(lvl['level'])" name="priority" class="form-control" data-toggle="tooltip" data-trigger="hover" data-placement="top" data-title="Priority">
						<option ng-repeat="l in lvl['vals']" value="@{{l.id}}">@{{l.name}}</option>
					</select>
				</div>
			</div>

			<div class="form-actions">
				<button type="submit" ng-disabled="basicSubmitDisabled()" class="btn btn-primary">
					<i class="icon-check2"></i> Save
				</button>
			</div>
		</form>
		</div>



	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.6/angular.min.js"></script>
	<script src="{{asset('admin-assets/product.js')}}"></script>
	@endsection

resources/views/admin/product/list.blade.php
@extends('layouts.admin')

@section('body')
 <div class="app-content content container-fluid">
      <div class="content-wrapper">
        <div class="content-header row">
          <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title"><a href="{{URL::to('admin/products')}}" class="btn btn-success">All Products</a></h2>
          </div>
          <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
            <div class="breadcrumb-wrapper col-xs-12">
              <ol class="breadcrumb">
                 <li class="breadcrumb-item"><form action="{{URL::to('admin/products/search')}}" method="GET"><input type="text" name="key" placeholder="Search for Product" class="form-control"/><input type="submit" style="display: none" /> </form>
                </li>
                <li class="breadcrumb-item"><a href="{{URL::to('admin/products/create')}}" id="addproduct"class="btn btn-success">Add Product</a>
                </li>
              
                
              </ol>
            </div>
          </div>
        </div>
      
<div class="row">
@foreach($products as $p)
	<div class="col-xl-3 col-md-6 col-sm-12">
			<div class="card">
				<div class="card-body">
					<div class="card-block">
            @if($p->productimages->count()!=0)
						<img class="card-img img-fluid mb-1" src="{{ route('asset1', ['admin-assets','uploads',$p->productimages->first()->image,800,600]) }}" alt="{{asset('admin-assets/app-assets/images/carousel/08.jpg')}}">
						@else
            <img class="card-img img-fluid mb-1" src="{{asset('admin-assets/app-assets/images/carousel/08.jpg')}}">
            @endif
            <h4 class="card-title">{{$p->name}}</h4>
            <h6><a href="{{URL::to('/admin/products/changefeatured'.'/'.$p->id)}}"><i>({{!$p->featured?"Not Featured": "Featured"}})</i></a>
                <a href="{{URL::to('/admin/products/changestatus'.'/'.$p->id)}}"><i>({{$p->status}})</i></a>

            </h6>
						<p class="card-text">{{substr($p->description,0,60)}}...</p>
						
           <form action="{{ route('products.destroy',$p->id) }}" method="POST">
               <a href="{{URL::to('admin/products'.'/'.$p->id.'/'.'edit')}}" class="btn btn-outline-teal" >Edit</a>

                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE" >
                <button id='deleteProduct{{$p->id}}' type="button" class="btn btn-outline-danger">Delete</button>
           
            </form>
          </div>
				</div>
			</div>
		</div>
@endforeach
</div>

</div>
</div>
</div>

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  
<script src="{{asset('jqueryTree/jquery.mjs.nestedSortable.js')}}"></script>
@endsection