routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//general routes
Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/brand/{name}','Frontend\ProductController@brand');
Route::get('/products','Frontend\ProductController@index');
Route::get('/products/search','Frontend\ProductController@search');
Route::get('/singleproduct','Frontend\ProductController@singleProduct');

Route::get('/services', 'Frontend\FrontendController@services')->name('services');
Route::post('/sendServiceMessage', 'Frontend\FrontendController@sendServiceMessage')->name('sendServiceMessage');

Route::get('/get-a-quote', 'Frontend\FrontendController@getQuote')->name('getQuote');
Route::post('/sendquote', 'Frontend\FrontendController@sendQuote')->name('sendQuote');
Route::post('/getProducts', 'Frontend\FrontendController@getProducts')->name('getProducts');

Route::get('/contact', 'Frontend\FrontendController@contact')->name('contact');
Route::post('/contactSend', 'Frontend\FrontendController@contactSend')->name('contactSend');

Route::get('/about', 'Frontend\FrontendController@about')->name('about');

Route::get('/gallery/albums','Frontend\FrontendController@albums')->name('gallery.albums');
Route::get('/gallery/album/{slug}', 'Frontend\FrontendController@album')->name('gallery.album');

Route::post('/subscribe','HomeController@subscribe')->name('subscribe');
Route::get('unsubscribe/{token}','HomeController@unsubscribe')->name('unsubscribe');
Route::post('unsubscribe/{token}','HomeController@unsubscribed')->name('unsubscribed');

Route::get('/home', 'HomeController@index')->name('home');


//routes for admin
Route::prefix('admin')->group(function(){
    Auth::routes();

    Route::get('staffs','Admin\StaffController@index')->name('staffs.index');
    Route::post('staffs/update','Admin\StaffController@update')->name('staffs.update');    
    Route::post('staffs/delete/{id}','Admin\StaffController@destroy')->name('staffs.destroy');
    Route::post('verifyPassword','Admin\StaffController@verifyPassword')->name('verifyPassword');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::resource('services', 'Admin\ServiceController',['except' => ['show']]);

    Route::get('quotations/unseen','Admin\QuotationController@unseenQuotes')->name('quotations.unseen');    
    Route::get('quotations/reply/{id}','Admin\QuotationController@reply')->name('quotations.reply');
    Route::post('quotations/reply/{id}','Admin\QuotationController@replySend')->name('quotations.replySend');
    Route::get('getUnseenQuoteCount','Admin\QuotationController@getUnseenQuoteCount')->name('getUnseenQuoteCount');
    Route::get('getUnseenQuote','Admin\QuotationController@getUnseenQuote')->name('getUnseenQuote');
    Route::resource('quotations', 'Admin\QuotationController',['only' => ['show','destroy','index']]);

    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');

    Route::resource('testimonials', 'Admin\TestimonialController',['only' => ['index','store','edit','update','destroy']]);

    Route::get('contact-us-messages/unseen','Admin\ContactController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactController@getUnseenMsg')->name('getUnseenMsg');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);
    
    Route::get('service-support-messages','Admin\ServiceSupportMessageController@addImages1')->name('service-support-messages.index');
    Route::get('service-support-messages/unseen','Admin\ServiceSupportMessageController@unseenMsg')->name('service-support-messages.unseen');    
    Route::get('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@reply')->name('service-support-messages.reply');
    Route::post('service-support-messages/reply/{id}','Admin\ServiceSupportMessageController@replySend')->name('service-support-messages.replySend');
    Route::resource('service-support-messages', 'Admin\ServiceSupportMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenSSMsgCount','Admin\ServiceSupportMessageController@getUnseenSSMsgCount')->name('getUnseenSSMsgCount');
    Route::get('getUnseenSSMsg','Admin\ServiceSupportMessageController@getUnseenSSMsg')->name('getUnseenSSMsg');

    Route::get('/dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::get('/','Admin\AdminController@index');
    
    Route::get('/products/search','ProductController@search');
	Route::post('/products/addbasics','ProductController@addBasics');
	Route::post('/products/editbasics','ProductController@editBasics');
    Route::get('/products/getbrandsandsolutions','ProductController@getBrandsAndSolutions');
	Route::post('/products/addimage/{id}','ProductController@addImage');
    Route::post('/products/removeimage','ProductController@removeImage');
    Route::resource('/products','ProductController');
    Route::post('/products/savefeatures','ProductController@saveFeatures');
    Route::post('/products/savespecification','ProductController@saveSpecification');
    Route::post('/products/savepurpose','ProductController@savePurpose');
    Route::post('/products/savefaqs','ProductController@saveFaqs');
    Route::post('/products/adddriver','ProductController@adddriver');
    Route::post('/products/savedriver','ProductController@savedriver');
    Route::post('/products/removedriver','ProductController@removedriver');
    Route::get('/products/changefeatured/{id}','ProductController@changeFeatured'); 
    Route::get('/products/changestatus/{id}','ProductController@changeStatus'); 
   
	Route::post('/brands/createmainbrand','BrandController@createMainBrand');
    Route::post('/brands/createbrand','BrandController@createBrand');
    Route::get('/brands','BrandController@index')->name('brands.index');
	Route::get('/brands/getbrands','BrandController@getBrands');
	Route::get('/brands/brandsbyid','BrandController@getSingleBrand');
    Route::post('/brands/savebrand','BrandController@saveBrand');
    Route::post('/brands/create','BrandController@addBrand');
	Route::post('/brands/edit','BrandController@editBrand');
	Route::post('/brands/editParent','BrandController@editBrandParent');
	Route::post('/brands/delete','BrandController@deleteBrand');
    Route::get('/brands/editmainbrand/{id}','BrandController@editMainBrand');
    Route::delete('/brands/removeImage/{id}','BrandController@removeImage')->name('admin.brands.removeImage');
    Route::post('/brands/addImage/{id}','BrandController@addImage')->name('admin.brands.addImage');
    Route::post('/brands/haschild','BrandController@hasChild');


	Route::get('/solutions','SolutionController@index')->name('solutions.index');
    Route::get('/solutions/getsolutions','SolutionController@getSolutions');
    Route::get('/solutions/solutionsbyid','SolutionController@getSingleSolution');
    Route::post('/solutions/create','SolutionController@addSolution');
    Route::post('/solutions/edit','SolutionController@editSolution');
    Route::post('/solutions/editParent','SolutionController@editSolutionParent');
    Route::post('/solutions/delete','SolutionController@deleteSolution');
    Route::post('/solutions/createSolution','SolutionController@createSolution');
    Route::post('/solutions/haschild','SolutionController@hasChild');    
});

Route::get('/assets/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response('jpg');
})->name('asset');
Route::get('/assets/{source}/{source2}/{img}/{h}/{w}',function($source,$source2,$img, $h, $w){
   
    return \Image::make(public_path("/".$source."/".$source2."/".$img))->resize($h, $w)->response('jpg');
})->name('asset1');
Route::get('/asset/{source}/{img}/{ext}/{h}/{w}',function($source,$img,$ext, $h, $w){
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('asset2');

resources/views/admin/partials/header.blade.php
<!DOCTYPE html>
<html lang="en" data-textdirection="ltr" class="loading">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Robust admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, robust admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>ShresthaAT {{$title}}</title>
    <link rel="apple-touch-icon" sizes="60x60" href="{{asset('admin-assets/app-assets/images/ico/apple-icon-60.png')}}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{asset('admin-assets/app-assets/images/ico/apple-icon-76.png')}}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{asset('admin-assets/app-assets/images/ico/apple-icon-120.png')}}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{asset('admin-assets/app-assets/images/ico/apple-icon-152.png')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('admin-assets/app-assets/images/ico/favicon.ico')}}">
    <link rel="shortcut icon" type="image/png" href="{{asset('admin-assets/app-assets/images/ico/favicon-32.png')}}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/bootstrap.css')}}">
    
    <!-- font icons-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/fonts/icomoon.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/fonts/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/vendors/css/extensions/pace.css')}}">
    <!-- END VENDOR CSS-->
  
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/bootstrap-extended.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/app.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/colors.css')}}">
    <!-- END ROBUST CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/core/menu/menu-types/vertical-overlay-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/app-assets/css/core/colors/palette-gradient.css')}}">
    <!-- END Page Level CSS-->
    
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin-assets/assets/css/style.css')}}">
    <!-- END Custom CSS-->
    @yield('css')
    <link rel="stylesheet" type="text/css" href="{{asset('sweetprompt/lib/sweetalert2.css')}}">
</head>

resources/views/admin/partials/mnotis.blade.php
@if($mno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new messages</p>
@endif
@foreach($messages as $m)
    <?php 
    $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($m->created_at))->diffForHumans();
    ?>
    <a href="{{ route('contact-us-messages.show',$m->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="/admin-assets/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar"><i></i></span></div>
        <div class="media-body">
        <h6 class="media-heading">{{ $m->name }}</h6>
        <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">Says "{{ $m->subject }}"</p><small>
            <time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach

resources/views/admin/partials/navbar.blade.php
 <body data-open="click" data-menu="vertical-menu" data-col="2-columns" class="vertical-layout vertical-menu 2-columns  fixed-navbar">

    <!-- navbar-fixed-top-->
    <nav class="header-navbar navbar navbar-with-menu navbar-fixed-top navbar-semi-dark navbar-shadow">
      <div class="navbar-wrapper">
        <div class="navbar-header">
          <ul class="nav navbar-nav">
            <li class="nav-item mobile-menu hidden-md-up float-xs-left"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5 font-large-1"></i></a></li>
            <li class="nav-item"><a href="" class="navbar-brand nav-link"><img alt="branding logo" src="{{ route('asset', ['images','SATLOGO.jpg',117,25]) }}" data-expand="{{ route('asset', ['images','SATLOGO.jpg',117,25]) }}" data-collapse="{{ route('asset', ['images','SATLOGO.jpg',32,18]) }}" class="brand-logo"></a></li>
            <li class="nav-item hidden-md-up float-xs-right"><a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container"><i class="icon-ellipsis pe-2x icon-icon-rotate-right-right"></i></a></li>
          </ul>
        </div>
        <div class="navbar-container content container-fluid">
          <div id="navbar-mobile" class="collapse navbar-toggleable-sm">
            <ul class="nav navbar-nav">
              <li class="nav-item hidden-sm-down"><a class="nav-link nav-menu-main menu-toggle hidden-xs"><i class="icon-menu5">         </i></a></li>
              <li class="nav-item hidden-sm-down"><a href="#" class="nav-link nav-link-expand"><i class="ficon icon-expand2"></i></a></li>
            </ul>
            <ul class="nav navbar-nav float-xs-right">
              @if(Auth::user()->roles()->where('title', '=', 'Service Support Messages')->exists())
                <li class="dropdown dropdown-notification nav-item"><a href="#" data-toggle="dropdown" class="nav-link nav-link-label" onclick="getUnseenSSMsg()"><i class="ficon icon-android-mail"></i><span class="tag tag-pill tag-default tag-danger tag-default tag-up" id="sno1">{{ $sno }}</span></a>
                  <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                    <li class="dropdown-menu-header">
                      <h6 class="dropdown-header m-0"><span class="grey darken-2">Service Support Messages</span><span class="notification-tag tag tag-default tag-danger float-xs-right m-0" id="sno2">{{ $sno }} New</span></h6>
                    </li>
                    <li class="list-group scrollable-container" id="Snotis">
                      @if($sno == 0)
                          <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new messages</p>
                      @endif
                    </li>
                    <li class="dropdown-menu-footer"><a href="{{ route('service-support-messages.unseen') }}" class="dropdown-item text-muted text-xs-center">Read all new messages</a></li>
                  </ul>
                </li>
              @endif
              @if(Auth::user()->roles()->where('title', '=', 'Quotations')->exists())
                <li class="dropdown dropdown-notification nav-item"><a href="#" data-toggle="dropdown" class="nav-link nav-link-label" onclick="getUnseenQuote()"><i class="ficon icon-bell4"></i><span class="tag tag-pill tag-default tag-danger tag-default tag-up" id="qno1">{{ $qno }}</span></a>
                  <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                    <li class="dropdown-menu-header">
                      <h6 class="dropdown-header m-0"><span class="grey darken-2">Quotations</span><span class="notification-tag tag tag-default tag-danger float-xs-right m-0" id="qno2">{{ $qno }} New</span></h6>
                    </li>
                    <li class="list-group scrollable-container" id="Qnotis">
                      
                    </li>
                    <li class="dropdown-menu-footer"><a href="{{ route('quotations.unseen') }}" class="dropdown-item text-muted text-xs-center">Read all new quotations</a></li>
                  </ul>
                </li>
              @endif
          
              @if(Auth::user()->roles()->where('title', '=', 'Contact Us Messages')->exists())
                <li class="dropdown dropdown-notification nav-item"><a href="#" onclick="getUnseenMsg()" data-toggle="dropdown" class="nav-link nav-link-label"><i class="ficon icon-mail6"></i><span class="tag tag-pill tag-default tag-info tag-default tag-up" id="mno1">{{ $mno }}</span></a>
                  <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                    <li class="dropdown-menu-header">
                      <h6 class="dropdown-header m-0"><span class="grey darken-2">Contact Us Messages</span><span class="notification-tag tag tag-default tag-info float-xs-right m-0" id="mno2">{{ $mno }} New</span></h6>
                    </li>
                    <li class="list-group scrollable-container" id="Mnotis">
                      
                    </li>
                    <li class="dropdown-menu-footer"><a href="{{ route('contact-us-messages.unseen') }}" class="dropdown-item text-muted text-xs-center">Read all new messages</a></li>
                  </ul>
                </li>
              @endif  
              
              <li class="dropdown dropdown-user nav-item"><a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link"><span class="avatar avatar-online"><img src="{{ route('asset2', ['images','avatar.png','png',30,30]) }}" alt="avatar"><i></i></span><span class="user-name" id="adminName">{{ Auth::user()->name }}</span></a>
                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{{ route('profile') }}" class="dropdown-item"><i class="icon-head"></i> Edit Profile</a>
                  <div class="dropdown-divider"></div>
                  <a href="{{ url('/admin/logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();" class="dropdown-item">
                  <i class="icon-power3"></i> Logout</a>
                  <form id="logout-form" action="{{ url('/admin/logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                  </form>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <!-- ////////////////////////////////////////////////////////////////////////////-->


    <!-- main menu-->
    <div data-scroll-to-active="true" class="main-menu menu-fixed menu-dark menu-accordion menu-shadow">
      
      <!-- main menu content-->
      <div class="main-menu-content">
        <ul id="main-menu-navigation" data-menu="menu-navigation" class="navigation navigation-main">
          <br>
          <li id="dashboard" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Dashboard')->exists() ? '':'hidden'}}"><a href="{{ route('admin_dashboard') }}"><i class="icon-home3"></i><span data-i18n="nav.dash.main" class="menu-title">Dashboard</span></a>
          </li>
      
          <li id="staffs" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Staffs')->exists() ? '':'hidden'}}"><a href="{{ route('staffs.index') }}"><i class="icon-android-contacts"></i><span data-i18n="nav.staffs.main" class="menu-title">Staffs</span></a>
          </li>

          <li id="brands" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Brands')->exists() ? '':'hidden'}}"><a href="{{ route('brands.index') }}"><i class="icon-tag"></i><span data-i18n="nav.brands.main" class="menu-title">Brands</span></a>
          </li>

          <li id="products" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Products')->exists() ? '':'hidden'}}"><a href="{{ route('products.index') }}"><i class="icon-product-hunt"></i><span data-i18n="nav.products.main" class="menu-title">Products</span></a>
          </li>

          <li id="solutions" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Solutions')->exists() ? '':'hidden'}}"><a href="{{ route('solutions.index') }}"><i class="icon-lightbulb-o"></i><span data-i18n="nav.solutions.main" class="menu-title">Solutions</span></a>
          </li>

          <li id="services" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Services')->exists() ? '':'hidden'}}"><a href="{{ route('services.index') }}"><i class="icon-gears"></i><span data-i18n="nav.services.main" class="menu-title">Services</span></a>
          </li>

          <li id="quotations" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Quotations')->exists() ? '':'hidden'}}"><a href="{{ route('quotations.index') }}"><i class="icon-document-text"></i><span data-i18n="nav.quotations.main" class="menu-title">Quotations</span></a>
          </li>

          <li id="albums" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Albums')->exists() ? '':'hidden'}}"><a href="{{ route('albums.index') }}"><i class="icon-image3"></i><span data-i18n="nav.albums.main" class="menu-title">Albums</span></a>
          </li>

          <li id="newsletter" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Newsletter')->exists() ? '':'hidden'}}"><a href="{{ route('newsletter') }}"><i class="icon-mail6"></i><span data-i18n="nav.newsletter.main" class="menu-title">Newsletter</span></a>
          </li>

          <li id="testimonials" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Testimonials')->exists() ? '':'hidden'}}"><a href="{{ route('testimonials.index') }}"><i class="icon-commenting"></i><span data-i18n="nav.testimonials.main" class="menu-title">Testimonials</span></a>
          </li>

          <li id="contact-us-messages" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Contact Us Messages')->exists() ? '':'hidden'}}"><a href="{{ route('contact-us-messages.index') }}"><i class="icon-at2"></i><span data-i18n="nav.contact-us-messages.main" class="menu-title">Contact Messages</span></a>
          </li>

          <li id="settings" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Settings')->exists() ? '':'hidden'}}"><a href="{{ route('admin.settings') }}"><i class="icon-gear"></i><span data-i18n="nav.settings.main" class="menu-title">Settings</span></a>
          </li>

          <li id="service-support-messages" class="nav-item {{Auth::user()->roles()->where('title', '=', 'Service Support Messages')->exists() ? '':'hidden'}}"><a href="{{ route('service-support-messages.index') }}"><i class="icon-support"></i><span data-i18n="nav.service-support-messages.main" class="menu-title">Service Support Messages</span></a>
          </li>

          
        </ul>
      </div>
      <!-- /main menu content-->
      <!-- main menu footer-->
      <!-- include includes/menu-footer-->
      <!-- main menu footer-->
    </div>
    <!-- / main menu-->

resources/views/admin/partials/qnotis.blade.php
@if($qno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new quotations</p>
@endif
@foreach($quotes as $q)
    <?php 
        $pro_count = count(json_decode($q->quote_items)); 
        $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($q->created_at))->diffForHumans();
    ?>
    <a href="{{ route('quotations.show',$q->id) }}" class="list-group-item">
        <div class="media">
            <div class="media-left valign-middle"><i class="icon-cart3 icon-bg-circle bg-cyan"></i></div>
            <div class="media-body">
            <h6 class="media-heading">You have new quotation Q{{ 100+$q->id }}!</h6>
            <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">{{ $q->customer_name }} has requested a quotation for {{ $pro_count }} different types of products.</p><small>
                <time class="media-meta text-muted">{{ $interval }}</time></small>
            </div>
        </div>
    </a>
@endforeach

resources/views/admin/partials/snotis.blade.php
@if($sno == 0)
    <p class="notification-text font-small-3 text-muted text-xs-center" style="margin:20px">No new messages</p>
@endif
@foreach($messages as $m)
    <?php 
    $interval = \Carbon\Carbon::createFromTimeStamp(strtotime($m->created_at))->diffForHumans();
    ?>
    <a href="{{ route('service-support-messages.show',$m->id) }}" class="list-group-item">
    <div class="media">
        <div class="media-left"><span class="avatar avatar-sm avatar-online rounded-circle"><img src="/admin-assets/app-assets/images/portrait/small/avatar-s-1.png" alt="avatar"><i></i></span></div>
        <div class="media-body">
            <h6 class="media-heading">{{ $m->name }}</h6>
            <p class="notification-text font-small-3 text-muted" style="line-height:1.2em">Sent "{{ $m->subject }}" To {{ $m->sentTo }}</p>
            <small><time class="media-meta text-muted">{{ $interval }}</time></small>
        </div>
    </div>
    </a>
@endforeach